const dogs = [
  {
    id: 20006,
    imgSrc: "pink.png",
    name: "Pink",
    age: "3 years",
    sex: "Male",
    breed: "Podenca Maneta X",
    size: "Small",
  },
  {
    id: 19523,
    imgSrc: "toreto.png",
    name: "Toreto",
    age: "7 years",
    sex: "Male",
    breed: "Amorosos Cabezones",
    size: "Medium",
  },
  {
    id: 20466,
    imgSrc: "fitipaldi.png",
    name: "Fitipaldi",
    age: "2 years",
    sex: "Male",
    breed: "Podenco",
    size: "Medium",
  },
  {
    id: 19020,
    imgSrc: "simba.png",
    name: "Simba",
    age: "1 year",
    sex: "Male",
    breed: "Cruzado",
    size: "Medium",
  },
  {
    id: 16684,
    imgSrc: "jacobo.png",
    name: "Jacobo",
    age: "2 years",
    sex: "Male",
    breed: "Cruzado",
    size: "Big",
  },
  {
    id: 20529,
    imgSrc: "marchas.png",
    name: "Marchas",
    age: "1 year",
    sex: "Male",
    breed: "Mestizo",
    size: "Medium",
  },
  {
    id: 19618,
    imgSrc: "bruno.png",
    name: "Bruno",
    age: "4 years",
    sex: "Male",
    breed: "Cocker X",
    size: "Medium",
  },
  {
    id: 20440,
    imgSrc: "china.png",
    name: "China",
    age: "5 years",
    sex: "Female",
    breed: "Podenco",
    size: "Medium",
  },
  {
    id: 19493,
    imgSrc: "yuma.png",
    name: "Yuma",
    age: "2 years",
    sex: "Female",
    breed: "Mestizo",
    size: "Grande",
  },
];

export default dogs;
